### ISSUE TITLE
docs: how to run this locally?

### ISSUE THREAD

**Issue by guaka** [kumavis/ethereum-simulator#10]
tried some things in vain, some docs would be nice

**Comment by k1n0k0** [comment]
Hey thanks for trying it out! sorry for the trouble

I updated the readme and the dependencies. Give it another go and let me know if you are successful. If you're still having trouble please post the err messages etc. :cactus:

**Comment by guaka** [comment]
Great, I didn't know about `npm start`. I had to `npm install -g beefy` to get a bit further, then got stuck here:

```
$ npm start

> ethereum-simulator@0.0.1 start ethereum/ethereum-simulator
> beefy app.js:bundle.js --open --live -- -t brfs

listening on http://localhost:8000/
200    9ms      371B /index.html
200    7ms    1.08KB /assets/reset.css
200    1ms    2.39KB /assets/app.css

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

npm ERR! ethereum-simulator@0.0.1 start: `beefy app.js:bundle.js --open --live -- -t brfs`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the ethereum-simulator@0.0.1 start script.
npm ERR! This is most likely a problem with the ethereum-simulator package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     beefy app.js:bundle.js --open --live -- -t brfs
npm ERR! You can get their info via:
npm ERR!     npm owner ls ethereum-simulator
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd ethereum/ethereum-simulator
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     ethereum/ethereum-simulator/npm-debug.log
npm ERR! not ok code 0
```

```
$ more ethereum/ethereum-simulator/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@1.3.21
3 info using node@v0.10.24
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart ethereum-simulator@0.0.1
6 info start ethereum-simulator@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info ethereum-simulator@0.0.1 Failed to exec start script
9 error ethereum-simulator@0.0.1 start: `beefy app.js:bundle.js --open --live -- -t brfs`
9 error Exit status 8
10 error Failed at the ethereum-simulator@0.0.1 start script.
10 error This is most likely a problem with the ethereum-simulator package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     beefy app.js:bundle.js --open --live -- -t brfs
10 error You can get their info via:
10 error     npm owner ls ethereum-simulator
10 error There is likely additional logging output above.
11 error System Darwin 13.1.0
12 error command "node" "/usr/local/bin/npm" "start"
13 error cwd ethereum/ethereum-simulator
14 error node -v v0.10.24
15 error npm -v 1.3.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]
```

**Comment by k1n0k0** [comment]
if you pull latest and do `npm install` again, it may solve this

I cannot tell from the readout here what the problem is

**Comment by guaka** [comment]
Cool, running `npm install` again did the trick!
